[tools]
bun = "latest"
gemini-cli = "latest"
node = "24"
"npm:@bomb.sh/tab" = "latest"
"npm:@fresh-editor/fresh-editor" = "latest"
pitchfork = "latest"
turbo = "latest"
usage = "latest"
watchexec = "latest"

[settings]
experimental = true
